trigger:
  name: ${trigger_name}
  identifier: ${trigger_identifier}
  projectIdentifier: ${project_identifier}
  orgIdentifier: ${org_identifier}
  pipelineIdentifier: ${pipeline_identifier}
  enabled: true
  description: ""
  tags: {}
  stagesToExecute: []
  source:
    type: Webhook
    spec:
      type: Harness
      spec:
        type: PullRequest
        spec:
          connectorRef: ""
          autoAbortPreviousExecutions: false
          payloadConditions:
            - key: targetBranch
              operator: Equals
              value: main
          headerConditions: []
          repoName: my-backend-service
          actions:
            - Merge
            - Create
            - Update
            - Comment
  inputYaml: |
    pipeline:
      identifier: ${pipeline_identifier}
      properties:
        ci:
          codebase:
            build:
              type: PR
              spec:
                number: <+trigger.prNumber>
